version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependências necessárias..."
      - pip install --upgrade pip
      - pip install jq --quiet || true  # caso queira usar jq no ambiente

  build:
    commands:
      - echo "Procurando lambdas em lambda_src..."
      - |
        for dir in lambda_src/*; do
          echo "Processando lambda em $dir"

          # Lê o nome da função do JSON
          FUNCTION_NAME=$(jq -r .function_name "$dir/lambda.json")

          # Navega para a pasta da lambda e zipa tudo
          cd $dir
          zip -r function.zip .

          # Atualiza a função no AWS Lambda
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://function.zip \
            --region us-east-1

          cd -
        done
